/******************************************************************************
 * Traefik route publisher.
 *
 * PocketHost gives every PocketBase instance its own subdomain
 * (`<subdomain>.<APEX_DOMAIN>`). Coolify's proxy (Traefik v3) discovers routes
 * from Docker labels, which are fixed at deploy time, and a wildcard router
 * would only ever serve its fallback certificate — so instead this sidecar
 * polls the mothership for the instance list and writes one HTTPS router per
 * instance into Traefik's watched dynamic directory. Traefik then obtains a
 * normal Let's Encrypt certificate per instance host through the HTTP-01
 * challenge, exactly as it does for the dashboard and the mothership.
 *
 * Everything is written to a single file, so the feature can be disabled at any
 * time by deleting that file. Only hostnames under APEX_DOMAIN are emitted.
 ******************************************************************************/
import { mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { hostname, networkInterfaces } from 'node:os'
import { setTimeout as sleep } from 'node:timers/promises'

const MOTHERSHIP_URL = (process.env.MOTHERSHIP_URL || 'http://127.0.0.1:8090').replace(/\/$/, '')
const ADMIN_USERNAME = process.env.MOTHERSHIP_ADMIN_USERNAME || ''
const ADMIN_PASSWORD = process.env.MOTHERSHIP_ADMIN_PASSWORD || ''
const APEX_DOMAIN = (process.env.APEX_DOMAIN || '').replace(/^\./, '').toLowerCase()
const DAEMON_PORT = Number(process.env.DAEMON_PORT || 3000)
const DYNAMIC_DIR = process.env.TRAEFIK_DYNAMIC_DIR || '/traefik-dynamic'
const DYNAMIC_FILE = process.env.TRAEFIK_DYNAMIC_FILE || 'pockethost.yaml'
const SYNC_INTERVAL_MS = Number(process.env.TRAEFIK_SYNC_INTERVAL_MS || 20000)
const CERT_RESOLVER = process.env.TRAEFIK_CERT_RESOLVER || 'letsencrypt'
const MIDDLEWARE_NAME = 'pockethost-redirect-to-https'

const log = (...args) => console.log('[traefik-sync]', ...args)
const warn = (...args) => console.warn('[traefik-sync]', ...args)

/** Address the proxy can reach this container's daemon on. */
const backendHost = () => {
  if (process.env.TRAEFIK_BACKEND_HOST) return process.env.TRAEFIK_BACKEND_HOST
  for (const addrs of Object.values(networkInterfaces())) {
    for (const addr of addrs || []) {
      if (addr.family === 'IPv4' && !addr.internal) return addr.address
    }
  }
  return hostname()
}

const BACKEND_HOST = backendHost()

const authenticate = async () => {
  const body = JSON.stringify({ identity: ADMIN_USERNAME, password: ADMIN_PASSWORD })
  const headers = { 'Content-Type': 'application/json' }

  for (const path of [
    '/api/collections/_superusers/auth-with-password',
    '/api/admins/auth-with-password',
  ]) {
    const res = await fetch(`${MOTHERSHIP_URL}${path}`, { method: 'POST', headers, body })
    if (res.ok) {
      const data = await res.json()
      if (data.token) return data.token
    } else if (res.status !== 404 && res.status !== 400) {
      warn(`auth against ${path} failed: ${res.status}`)
    }
  }
  throw new Error('could not authenticate against the mothership')
}

/** Every instance that should be publicly routed. */
const fetchInstanceHosts = async (token) => {
  const res = await fetch(
    `${MOTHERSHIP_URL}/api/collections/instances/records?perPage=500&fields=id,subdomain,cname,dev,suspension`,
    { headers: { Authorization: token } }
  )
  if (res.status === 401 || res.status === 403) throw new Error('unauthorized')
  if (!res.ok) throw new Error(`instances request failed: ${res.status}`)

  const data = await res.json()
  return [
    ...new Set(
      (data.items || [])
        .filter((item) => !item.dev && !item.suspension)
        .map((item) => ((item.cname || '').trim() || `${item.subdomain}.${APEX_DOMAIN}`).toLowerCase())
        .filter((host) => host.endsWith(`.${APEX_DOMAIN}`))
    ),
  ].sort()
}

const renderYaml = (hosts) => {
  const lines = [
    '# Generated by the PocketHost stack (docker/traefik-sync.mjs) — do not edit by hand.',
    `# backend http://${BACKEND_HOST}:${DAEMON_PORT} | instances ${hosts.length}`,
    'http:',
    '  middlewares:',
    `    ${MIDDLEWARE_NAME}:`,
    '      redirectScheme:',
    '        scheme: https',
    '        permanent: true',
    '  routers:',
  ]

  hosts.forEach((host, index) => {
    const name = `pockethost-instance-${index + 1}`
    lines.push(
      `    ${name}-https:`,
      `      rule: "Host(\`${host}\`)"`,
      '      service: pockethost-instances',
      '      entryPoints: ["https"]',
      '      priority: 10',
      '      tls:',
      `        certResolver: ${CERT_RESOLVER}`,
      `    ${name}-http:`,
      `      rule: "Host(\`${host}\`)"`,
      '      service: pockethost-instances',
      '      entryPoints: ["http"]',
      '      priority: 10',
      '      middlewares: ["' + MIDDLEWARE_NAME + '"]'
    )
  })

  // The backend service every router points at, declared *after* the routers. Emitting it before
  // them put the routers inside `services:` — the file still loaded, `routers:` was empty, and every
  // instance host answered 404 with a self-signed certificate. Order is the whole fix.
  lines.push(
    '  services:',
    '    pockethost-instances:',
    '      loadBalancer:',
    '        passHostHeader: true',
    '        servers:',
    `          - url: "http://${BACKEND_HOST}:${DAEMON_PORT}"`
  )

  return `${lines.join('\n')}\n`
}

/**
 * Fail loudly if the routers are not where Traefik looks for them.
 *
 * This exact mistake shipped once and looked like "instances are unreachable" rather than like a
 * config error, so the sync now checks its own output before declaring success: every expected host
 * must appear between `routers:` and `services:`, and not after it.
 */
const assertRoutersPlacedCorrectly = (yaml, hosts) => {
  const routersAt = yaml.indexOf('\n  routers:')
  const servicesAt = yaml.indexOf('\n  services:')
  if (routersAt === -1 || servicesAt === -1 || servicesAt < routersAt) {
    throw new Error('rendered routes are malformed: routers/services sections are missing or swapped')
  }
  for (const host of hosts) {
    const at = yaml.indexOf(`Host(\`${host}\`)`)
    if (at === -1 || at < routersAt || at > servicesAt) {
      throw new Error(`router for ${host} was emitted outside the routers section`)
    }
  }
}

const main = async () => {
  if (!APEX_DOMAIN) {
    warn('APEX_DOMAIN is not set — route publishing disabled')
    return
  }

  mkdirSync(DYNAMIC_DIR, { recursive: true })
  log(`publishing to ${DYNAMIC_DIR}/${DYNAMIC_FILE}, backend http://${BACKEND_HOST}:${DAEMON_PORT}`)

  let token = ''
  let lastWritten = ''

  for (;;) {
    try {
      if (!token) token = await authenticate()
      const hosts = await fetchInstanceHosts(token)
      const yaml = renderYaml(hosts)
      // Validate before writing: a malformed file must never replace a working one, and a bad render
      // must surface as a sync error rather than as instance hosts mysteriously 404ing.
      assertRoutersPlacedCorrectly(yaml, hosts)

      if (yaml !== lastWritten) {
        const target = `${DYNAMIC_DIR}/${DYNAMIC_FILE}`
        const tmp = `${target}.${process.pid}.tmp`
        writeFileSync(tmp, yaml)
        renameSync(tmp, target)
        lastWritten = yaml
        log(`published ${hosts.length} instance route(s)`)
      }
    } catch (e) {
      if (e.message === 'unauthorized') token = ''
      warn(`sync failed: ${e.message}`)
    }
    await sleep(SYNC_INTERVAL_MS)
  }
}

main().catch((e) => {
  warn(`fatal: ${e.message}`)
  process.exit(1)
})
